services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    environment:
      - FLASK_APP=lt_crm.app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/lt_crm
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - BABEL_DEFAULT_LOCALE=lt_LT
      - BABEL_DEFAULT_TIMEZONE=Europe/Vilnius
      - SECRET_KEY=local-dev-secret-key
    volumes:
      - ./lt_crm:/app/lt_crm
      - ./lt_crm/migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A lt_crm.app.celery_worker:celery worker --loglevel=info
    environment:
      - FLASK_APP=lt_crm.app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/lt_crm
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - BABEL_DEFAULT_LOCALE=lt_LT
      - BABEL_DEFAULT_TIMEZONE=Europe/Vilnius
      - SECRET_KEY=local-dev-secret-key
    volumes:
      - ./lt_crm:/app/lt_crm
      - ./lt_crm/migrations:/app/migrations
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lt_crm
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: 