# fly.toml app configuration file generated for lt-crm
app = "lt-crm"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_APP = "app"
  FLASK_ENV = "production"
  BABEL_DEFAULT_LOCALE = "lt_LT"
  BABEL_DEFAULT_TIMEZONE = "Europe/Vilnius"
  PROMETHEUS_MULTIPROC_DIR = "/tmp/prometheus"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 550
  soft_limit = 500

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "lt_crm_data"
  destination = "/data"

[metrics]
  port = 9091
  path = "/metrics"

[[statics]]
  guest_path = "/app/app/static"
  url_prefix = "/static/" 